[package]
name = "dessin_salon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.1"
plotters-svg = "0.3"
plotters-backend = "0.3"


